#condor_submit submit_ZHvar_production_clustered_highpt.sub
#condor_submit submit_DY_production_clustered_highpt.sub
condor_submit submit_TT_production_clustered_highpt.sub
condor_submit submit_ZHcc_production_clustered_highpt.sub
condor_submit submit_ZHbb_production_clustered_highpt.sub
condor_submit submit_XtoHH_500-1000_production_clustered_highpt.sub
condor_submit submit_XtoHH_1000-4000_production_clustered_highpt.sub